apiVersion: v2
name: external-dns
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
type: application
version: 1.10.1
appVersion: 0.12.0
keywords:
  - kubernetes
  - externaldns
  - external-dns
  - dns
  - service
  - ingress
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/img/external-dns.png
maintainers:
  - name: jacob_kim
    email: hello@jacob.kim
dependencies:
  - name: external-dns
    version: 1.10.1
    repository: https://kubernetes-sigs.github.io/external-dns/
