clusterName: central
clusterRegion: ap-northeast-2
infraAccountId: "765355018960"
rootNamespace: argocd

stage: central
defaultRepoURL: https://github.com/jacobhjkim/declarative-eks-tutorial
defaultTargetRevision: main
defaultProject: central-apps
destinationServer: https://kubernetes.default.svc

apps:
  - name: actions-runner-controller
    namespace: actions-runner-controller
    source:
      path: kubernetes/charts/actions-runner-controller
    valueFiles:
      - values-central.yaml
    skipCrds: false
    ignoreDifferences:
      - kind: Secret
        name: actions-runner-controller-serving-cert
        jsonPointers:
          - /data/ca.crt
          - /data/tls.crt
          - /data/tls.key
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/1/clientConfig/caBundle
          - /webhooks/2/clientConfig/caBundle
          - /webhooks/3/clientConfig/caBundle
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/1/clientConfig/caBundle
          - /webhooks/2/clientConfig/caBundle
  - name: cert-manager
    namespace: kube-system
    source:
      path: kubernetes/charts/cert-manager
    valueFiles:
      - values-central.yaml
