apiVersion: v2
name: karpenter
description: A Helm chart for Karpenter, an open-source node provisioning project built for Kubernetes.
type: application
version: 0.16.3
appVersion: 0.16.3
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
home: https://karpenter.sh/
icon: https://repository-images.githubusercontent.com/278480393/dab059c8-caa1-4b55-aaa7-3d30e47a5616
maintainers:
  - name: jacob_kim
    email: hello@jacob.kim
dependencies:
  - name: karpenter
    version: 0.16.3
    repository: https://charts.karpenter.sh/
