clusterName: dev

karpenter:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::295140746614:role/dev-karpenter-controller
  clusterName: dev
  clusterEndpoint: https://0E65B7780B81C21AFEBAD46DD6DF5C88.gr7.ap-northeast-2.eks.amazonaws.com
  aws:
    defaultInstanceProfile: KarpenterNodeInstanceProfile-dev
  logLevel: info

provisionerList:
  default:
    labels:
      nodeType: default
      nodeSubnet: private
    requirements:
      - key: "node.kubernetes.io/instance-type"
        operator: In
        values: [ "m6i.2xlarge" ]
      - key: "kubernetes.io/arch"
        operator: In
        values: [ "amd64" ]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: [ "spot" ]
    ttlSecondsAfterEmpty: 30
