apiVersion: v2
appVersion: v2.4.12
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 5.5.6
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: jacob_kim
    email: hello@jacob.kim
dependencies:
  - name: argo-cd
    version: 5.5.6
    repository: https://argoproj.github.io/argo-helm
  - name: redis-ha
    version: 4.22.2
    repository: https://dandydeveloper.github.io/charts/
    condition: redis-ha.enabled
