{{- range $_, $item := $.Values.clusterSecretStores.vault.items }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $item.name }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade,pre-delete,pre-rollback"
spec:
  provider:
    vault:
      server: {{ $.Values.clusterSecretStores.vault.endpoint }}
      path: {{ $item.path }}
      version: "v2"
      auth:
        kubernetes:
          mountPath: "k8s/{{ $.Values.clusterName }}-external-secrets"
          role: "external-secrets"
          serviceAccountRef:
            name: {{ $.Release.Name }}
            namespace: {{ $.Release.Namespace }}
---
{{- end }}
