apiVersion: v2
name: external-secrets
description: External secret management for Kubernetes
type: application
version: "0.5.8"
appVersion: "v0.5.8"
kubeVersion: ">= 1.19.0-0"
keywords:
  - kubernetes-external-secrets
  - secrets
home: https://github.com/external-secrets/external-secrets
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png
maintainers:
  - name: jacob_kim
    email: hello@jacob.kim
dependencies:
  - name: external-secrets
    version: 0.5.8
    repository: https://charts.external-secrets.io
