apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: admin.password
      remoteRef:
        key: argocd
        property: admin_password
    - secretKey: admin.passwordMtime
      remoteRef:
        key: argocd
        property: admin_passwordMtime
    - secretKey: server.secretkey
      remoteRef:
        key: argocd
        property: server_secretkey
    - secretKey: webhook.github.secret
      remoteRef:
        key: argocd
        property: webhook_github_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-repo
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: argocd
        property: github_token
  target:
    name: github-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: {{ .Values.git.url }}
        username: {{ .Values.git.username }}
        password: |
          {{ "{{- .token -}}" }}
---
{{- range .Values.clusters }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-cluster-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-kv-cluster
    kind: ClusterSecretStore
  data:
    - secretKey: config
      remoteRef:
        key: cluster/{{ .name }}/argocd
        property: argoconfig
    - secretKey: name
      remoteRef:
        key: cluster/{{ .name }}/argocd
        property: name
    - secretKey: server
      remoteRef:
        key: cluster/{{ .name }}/argocd
        property: server
  target:
    name: {{ .name }}-cluster-secret
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
{{- end }}
