apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: admin.password
      remoteRef:
        key: argocd
        property: admin.password
    - secretKey: admin.passwordMtime
      remoteRef:
        key: argocd
        property: admin.passwordMtime
    - secretKey: webhook.github.secret
      remoteRef:
        key: argocd
        property: webhook.github.secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-repo-creds
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: github
        property: username
    - secretKey: token
      remoteRef:
        key: github
        property: token
  target:
    name: github-repo-creds
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: "https://github.com/jacobhjkim"
        username: ""
        password: |
          {{ "{{- .token -}}" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: "https://github.com/jacobhjkim/declarative-eks"

{{- range .Values.clusters }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-cluster-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-kv-cluster
    kind: ClusterSecretStore
  data:
    - secretKey: config
      remoteRef:
        key: cluster/{{ .name }}/argocd
        property: argoconfig
    - secretKey: name
      remoteRef:
        key: cluster/{{ .name }}/argocd
        property: name
    - secretKey: server
      remoteRef:
        key: cluster/{{ .name }}/argocd
        property: server
  target:
    name: {{ .name }}-cluster-secret
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
{{- end }}
