apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-vcs-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: github_token
      remoteRef:
        key: atlantis
        property: atlantis_github_token
    - secretKey: github_secret
      remoteRef:
        key: atlantis
        property: webhook_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-vault-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: vault_token
      remoteRef:
        key: atlantis
        property: atlantis_vault_token
