apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "actions-runner-controller.secretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: github_token
      remoteRef:
        key: github
        property: actions_runner_controller_pat
  target:
    name: {{ include "actions-runner-controller.secretName" . }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "actions-runner-controller-github-webhook-server.secretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: github_token
      remoteRef:
        key: github
        property: actions_runner_controller_pat
    - secretKey: github_webhook_secret_token
      remoteRef:
        key: github
        property: webhook_secret
  target:
    name: {{ include "actions-runner-controller-github-webhook-server.secretName" . }}
