apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: github_token
      remoteRef:
        key: github_actions_runner
        property: github_actions_runner_controller_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-webhook-server
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-kv-central
    kind: ClusterSecretStore
  data:
    - secretKey: github_token
      remoteRef:
        key: github_actions_runner
        property: github_actions_runner_controller_token
    - secretKey: github_webhook_secret_token
      remoteRef:
        key: github_actions_runner
        property: webhook_secret
