apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Values.ghaRunner.name }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade,pre-delete,pre-rollback"
spec:
  replicas: 1
  template:
    spec:
      repository: {{ .Values.ghaRunner.repository }}
      serviceAccountName: {{ .Values.ghaRunner.name }}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ .Values.ghaRunner.name }}-autoscaler
  annotations:
    helm.sh/hook: "post-install,post-upgrade,pre-delete,pre-rollback"
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    name: {{ .Values.ghaRunner.name }}
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "5m"
