apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ghaRunner.name }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.infraAccountId }}:role/central-{{ .Values.ghaRunner.name }}
